Docs italia style
italia/docs.italia.it pull request #12
Opened 2018-05-04 10:04 UTC by paoloromolini

2018-05-04 11:10 UTC, pdavide commented on media/docsitalia/images/agid-logo-alt-bb.svg
> +<?xml version="1.0" encoding="utf-8"?>
Questo file è obsoleto, si può rimuovere.

2018-05-04 11:11 UTC, pdavide commented on media/docsitalia/images/agid-logo-bb.svg
> +<?xml version="1.0" encoding="utf-8"?>
Questo file è obsoleto, si può rimuovere.

2018-05-04 11:16 UTC, pdavide requested changes
Questi file sono obsoleti e si possono rimuovere:
- media/docsitalia/images/agid-logo-alt-bb.svg
- media/docsitalia/images/agid-logo-bb.svg
- media/docsitalia/images/bg-flat.jpg
- media/docsitalia/images/bg.jpg
- media/docsitalia/images/dt-logo-alt.svg
- media/docsitalia/images/governo-alt.svg
- media/docsitalia/images/logo-agid-alt.svg
- media/docsitalia/images/logo-it.svg
- media/docsitalia/images/sea_header.jpg

2018-05-04 11:43 UTC, francescozaia commented on readthedocs/templates/docsitalia/includes/scripts.html
> +    _paq.push(['setSiteId', '{{ site.piwik }}']);
Lo segno qui, ma vale anche per altri file: sono rimaste un po' di occorrenze di `{{ site.* }}` nel porting da Jekyll, consiglio di fare un find ovunque e sostituire con il dato corretto (visibile nel repo originale o sul sito live)

2018-05-04 11:45 UTC, pdavide approved these changes

2018-05-04 11:47 UTC, francescozaia commented on readthedocs/templates/docsitalia/includes/scripts.html
> +
Questa è una pulizia che dovremmo fare anche sul repo originale: non supportiamo più questi browser, per cui L1-L10 possono essere rimosse tranquillamente (anche perché si può notare che i path non sono corretti).

2018-05-04 11:57 UTC, paoloromolini commented on readthedocs/templates/docsitalia/includes/scripts.html
> +    _paq.push(['setSiteId', '{{ site.piwik }}']);
:+1:

2018-05-04 11:59 UTC, francescozaia requested changes
Ho lasciato un paio di commenti, niente di drammatico. Poi per me si può mergiare, però aspettiamo anche @xrmx.

2018-05-04 13:32 UTC, francescozaia approved these changes

2018-05-08 07:07 UTC, xrmx commented
@paoloromolini squasha tutto in un commit che mergiamo

2018-05-08 09:08 UTC, xrmx approved these changes

2018-05-08 09:28 UTC, merged