extend rtf conf.py tmpl
italia/docs.italia.it pull request #20
Opened 2018-05-16 09:51 UTC by paoloromolini

Extend doc_builder/conf.py.tmpl to add documents_settings.yml data

2018-05-16 09:55 UTC, xrmx requested changes
You lost a doc_builder in the template path

2018-05-16 09:56 UTC, xrmx commented on readthedocs/docsitalia/templates/conf.py.tmpl
> +context['extra_data'] = data
I'd call this docsitalia instead of extra_data

2018-05-16 10:23 UTC, xrmx commented on readthedocs/docsitalia/templates/conf.py.tmpl
> +context['extra_data'] = data
or docsitalia_data

2018-05-16 13:38 UTC, xrmx submitted a review, later dismissed

2018-05-16 16:18 UTC, xrmx requested changes
please squash so we can merge, thanks!

2018-05-16 16:18 UTC, xrmx commented on readthedocs/settings/base.py
> +            # docsitalia
move this back please

2018-05-18 11:05 UTC, yakky approved these changes

2018-05-18 14:31 UTC, xrmx approved these changes

2018-05-19 13:27 UTC, merged