#235 not passing default version in search
italia/docs.italia.it pull request #370
Opened 2019-11-07 12:16 UTC by Amanit

https://github.com/italia/docs.italia.it/issues/235
Search documents in all versions not only 'bozza'

2019-11-07 12:47 UTC, yakky commented
come funziona su RTD?
Nella gestione della versione non abbiamo modificato nulla, quindi mi sembra strano sia necessario intervenire in modo cosi pesante.
Così com'è questo codice comunque ha impatto troppo grosso sul codice upstream per poterlo mergiare, e deve essere aperto su RTD

2019-11-07 13:48 UTC, pauloxnet commented
In generale non sposterei il codice in utils per minimizzare le differenze con il codice di RTD e per facilitare il merge con il branch in cui stiamo apportando le modifiche della ricerca.

Per la logica aspetterei chiarimenti relativi all'obiettivo reale della issue #235

2019-11-07 14:47 UTC, Amanit commented
Allora in #235 la descrizione non c'entra niente con la problema. Perché per risolvere problema in descrizione bastava fare un reindex di ES.
Problema risolta in questo PR sta in questo messagio - https://github.com/italia/docs.italia.it/issues/235#issuecomment-443129633

2019-11-07 14:50 UTC, Amanit commented
Possiamo spostare _get_user_input_namedtuple da utils in views per avere meno problemi con i merge futuri.

2019-11-07 14:59 UTC, Amanit commented
In RTD sembra che la ricerca sempre va fatta in una versione solo. In 'latest' se non e' chiesto altro.

2019-11-07 15:11 UTC, yakky commented
Giustamente @pdavide segnala (https://github.com/italia/docs.italia.it/issues/235#issuecomment-443148779) che "La tua supposizione mi sembra sensata nell'ottica RTD per la quale latest è l'ultima versione, non la bozza. ", invece per noi la versione ha valore semantico anche se non hanno modificato il flusso
L'impatto è tutt'altro che banale, perché nel caso si tolga il filtro sulla versione `latest` l'unica possibilità che vedo per non duplicare i risultati è fare un filtro ex-post che restituisca "bozza" solo se non ci sono risultati "stable"
O in alternativa prendere questa decisione lato indicizzazione, dove abbiamo forse più margine di manovra

2019-11-07 15:12 UTC, yakky requested changes
@francescozaia segnala che deve verificare internamente qual è il risultato che vogliono, quindi per il momento blocco

2019-11-07 15:32 UTC, francescozaia commented
Aggiungo soltanto a futura memoria che:

> nel caso si tolga il filtro sulla versione latest l'unica possibilità che vedo per non duplicare i risultati è fare un filtro ex-post che restituisca "bozza" solo se non ci sono risultati "stable"

questo potrebbe non essere sufficiente nel caso di documenti che non hanno né versione `stabile`, né `bozza` (casi particolari ma che purtroppo già esistono, come ad esempio il [CAD](https://docs.italia.it/italia/piano-triennale-ict/codice-amministrazione-digitale-docs/)).

2019-11-08 14:23 UTC, yakky commented
> Aggiungo soltanto a futura memoria che:
> 
> > nel caso si tolga il filtro sulla versione latest l'unica possibilità che vedo per non duplicare i risultati è fare un filtro ex-post che restituisca "bozza" solo se non ci sono risultati "stable"
> 
> questo potrebbe non essere sufficiente nel caso di documenti che non hanno né versione `stabile`, né `bozza` (casi particolari ma che purtroppo già esistono, come ad esempio il [CAD](https://docs.italia.it/italia/piano-triennale-ict/codice-amministrazione-digitale-docs/)).

il punto principale è in realtà capire se agire lato indicizzazione o lato ricerca è se vogliamo indicizzare tutte le versioni ma restituirne solo una o se ne indicizziamo una sola (in entrambi in casi quale sia la logica di selezione della versione è un punto successivo).

Il secondo caso è più semplice (ma soprattutto più efficiente in termini di tempo di risposta)

In alternativa potremmo aggiungere un attributo `latest` valorizzato a true se si sta facendo la build della versione più recente (per un significato arbitrario di "più recente") e lato ricerca basta fare di default un filtro su quella

2019-11-19 15:27 UTC, yakky commented
Questo verrà gestito in 403
La lascio aperta comunque come riferimento

2019-11-22 11:57 UTC, pauloxnet commented
Ma questa PR è ancora valida ? Oppure andrà sostituita con la issue per la gestione delle "versioni" default ?

2019-11-24 22:09 UTC, yakky commented
> Ma questa PR è ancora valida ? Oppure andrà sostituita con la issue per la gestione delle "versioni" default ?

sarà superata dalla nuova gestione, ma teniamola aperta come riferimento finché non viene aperta l'altra

2019-12-13 15:13 UTC, pauloxnet commented
@yakky dopo l'apertura della #439 credo che qui possiamo chiudere ?

2019-12-13 15:21 UTC, yakky commented
@pauloxnet volevo lasciar fare agli automatismi di github visto che ho aggiornato la descrizione della 439

2019-12-14 17:03 UTC, closed without merging