#222 Initial import webhook
italia/docs.italia.it pull request #372
Opened 2019-11-11 16:31 UTC by Amanit

2019-11-12 07:46 UTC, yakky commented
@Amanit please add some context and check test failures

2019-11-17 15:05 UTC, yakky commented
@Amanit facendo un confronto dei template vedo che loro hanno semplicemente tolto dal template quel pezzo di avviso 

Controlla la diff fra 
https://github.com/italia/docs.italia.it/blob/italia-dev/readthedocs/templates/docsitalia/overrides/core/project_bar_base.html
e 
https://github.com/italia/docs.italia.it/blob/italia-dev/readthedocs/templates/core/project_bar_base.html

visto che in realtà gli webhook sono creati anche in modalità asincrona, ci basterebbe aggiornare il template o sbaglio?

2019-11-17 15:06 UTC, yakky requested changes
@Amanit facendo un confronto dei template vedo che loro hanno semplicemente tolto dal template quel pezzo di avviso 

Controlla la diff fra 
https://github.com/italia/docs.italia.it/blob/italia-dev/readthedocs/templates/docsitalia/overrides/core/project_bar_base.html
e 
https://github.com/italia/docs.italia.it/blob/italia-dev/readthedocs/templates/core/project_bar_base.html

visto che in realtà gli webhook sono creati anche in modalità asincrona, ci basterebbe aggiornare il template o sbaglio?

2019-11-19 10:24 UTC, Amanit commented
@yakky si lo hanno tolto in https://github.com/readthedocs/readthedocs.org/commit/cedda9bf538e41122f075ba00bee268dcff67a60
Ma se togliamo questo pezzo di avviso sarebbe piu scomodo a capire se Webhook e' impostato o no.

2019-11-19 15:26 UTC, yakky commented
@Amanit si ma cosi siamo allineati a come fanno loro, mi sembrerebbe più adeguato, non abbiamo problemi con la sincronia  e diminuiamo le nostre modifiche rispetto a upstream

2019-11-20 14:26 UTC, Amanit commented
@yakky ho tolto questo avviso e ho tornato il task asincrono.

2019-11-20 15:27 UTC, yakky approved these changes

2019-11-20 15:37 UTC, yakky commented
@francescozaia che ne dici come soluzione? in teoria questo nasconde eventuali errori di collegamento con github, ma è esattamente come RTD gestisce la cosa

2019-11-21 16:35 UTC, francescozaia approved these changes
Per una volta, atteniamoci alle bad practices di RTD 😄 (scherzi a parte, va bene così).

2019-11-22 08:26 UTC, Amanit commented
Allora faccio un rebase e lo mergio

2019-11-22 10:37 UTC, merged