Add missign projects migration
italia/docs.italia.it pull request #415
Opened 2019-11-20 13:28 UTC by pauloxnet

2019-11-20 15:28 UTC, yakky approved these changes

2019-11-20 15:30 UTC, yakky requested changes
è una migrazione mancante in RTD che hanno aggiunto dopo? Ne possiamo fare a meno al momento?

2019-11-20 16:11 UTC, pauloxnet commented
In realtà è una migrazione legata all'impostazione di 'bozza' in `RTD_LATEST` in un vecchio commit di @Amanit alla fine del quale ci sarebbe voluto un `makemigrations`
https://github.com/italia/docs.italia.it/commit/4cfcea41080a72f0a7319079e16bcb076f3c2929

La migrazione non credo faccia nessuna modifica al DB ma finchè non creiamo il file di migrazione la situazione tra il codice e le migrazioni è disallineata

2019-11-20 16:38 UTC, yakky commented
ah certo è il renaming di `LATEST` da `latest` a `bozza`
Vorrei gestire questa migrazione in modo diverso, me la assegno io per proporre un altro approccio

Avere un migrazione in `projects` rende molto laborioso un allineamento adeguato a upstream perché ci troveremmo una migrazione "fantasma", ma ho una soluzione, che vi sottoporrò :)

2019-11-20 16:57 UTC, pauloxnet commented
Ok, gestisci pure come preferisci, l'importante e che ricordiamo di tenerne conto.

2019-11-21 07:22 UTC, yakky commented
@pauloxnet ho fatto il push (d89961aa3f248b0d1be8ead1ad5d3b6b02fd650b) della possibile soluzione per tenere la migrazione in `docsitalia`

Le classi aggiunte sono delle estensioni delle corrispondenti classi di django per poter iniettare il nome della app su cui fare la migrazione
Le uso da diverso tempo senza mai aver incontrato problemi

2019-11-21 08:48 UTC, pauloxnet commented
@yakky mi fido del fatto che tu abbia testato questa procedura quindi mergiala pure.

Ti chiedo solo perchè hai aggiunto anche il command `patch-project-version` che non mi sembra faccia nulla o abbia relazioni nel contesto ?

2019-11-21 09:23 UTC, yakky commented
@pauloxnet errore mio (lanciato `create_command` invece di `makemigrations`), command rimosso

2019-11-21 09:26 UTC, pauloxnet commented
ok @yakky per me si può mergiare

2019-11-21 09:27 UTC, yakky submitted a review, later dismissed

2019-11-21 10:38 UTC, yakky approved these changes

2019-11-21 11:44 UTC, merged