Fix manifest file extension and image src path
italia/docs.italia.it pull request #428
Opened 2019-11-26 13:39 UTC by SimoneNephila

Fix #323

2019-11-27 16:35 UTC, francescozaia commented
Mi sa che anche il file stesso `manifest.webmanifest` non ha un path corretto perché non viene proprio pescato dal sito (vedi immagine allegata a https://github.com/italia/docs.italia.it/issues/323) (al momento viene cercato sotto https://docs.italia.it/media/docsitalia/icons/manifest.webmanifest ma torna un 404). Te lo segnalo perché non vedo modifiche in tal senso nella PR.

2019-12-03 22:51 UTC, yakky requested changes
@SimoneNephila puoi verificare il commento di francesco?

2019-12-10 15:37 UTC, SimoneNephila commented
@francescozaia @yakky In realtà il path del file che ho modificato è il seguente:
 media/docsitalia/icons/manifest.webmanifest 

Che in teoria equivale a quello che restituisce un 404..

2019-12-12 11:34 UTC, yakky approved these changes

2019-12-12 11:35 UTC, yakky commented
questa PR include anche il rename del file per ovviare al problema del 404 sul file manifest

2019-12-12 11:50 UTC, francescozaia approved these changes

2019-12-12 11:51 UTC, francescozaia commented
A me rimane il dubbio sul path (su https://old.dev.docs.italia.it/ torna 404 e in questa PR non vedo modifiche in tal senso), ma mi fido e ho approvato. :D

2019-12-12 12:18 UTC, merged