Fix tablet and mobile version of documents detail
italia/docs.italia.it pull request #437
Opened 2019-12-10 15:26 UTC by SimoneNephila

Fix #429 and #430

2019-12-12 10:25 UTC, yakky commented
@francescozaia questa review la lascio a te

2019-12-12 11:48 UTC, francescozaia submitted a review, later dismissed
Va tutto bene, vi chiederei solo una piccola review se magari riuscite ad evitare qualche dichiarazione nel CSS a favore dell'utilizzo delle classi di Bootstrap dedicate a [flex](https://italia.github.io/bootstrap-italia/docs/organizzare-gli-spazi/flex/) o [padding e margini](https://italia.github.io/bootstrap-italia/docs/organizzare-gli-spazi/spaziature/).

2019-12-12 12:19 UTC, yakky requested changes
> Va tutto bene, vi chiederei solo una piccola review se magari riuscite ad evitare qualche dichiarazione nel CSS a favore dell'utilizzo delle classi di Bootstrap dedicate a [flex](https://italia.github.io/bootstrap-italia/docs/organizzare-gli-spazi/flex/) o [padding e margini](https://italia.github.io/bootstrap-italia/docs/organizzare-gli-spazi/spaziature/).

@SimoneNephila

2019-12-13 09:35 UTC, francescozaia commented
@yakky si può comunque mergiare, il mio era giusto un appunto (occhio ai conflitti su `core.css`).

2019-12-13 10:08 UTC, SimoneNephila commented
@francescozaia Sto riportando le varie classi ed eliminando gli stili superflui, in prima battuta mi è tornato più "comodo" usare il css. Una volta finito qua e controllato che non si rompa nulla pusho un altro commit

2019-12-14 15:24 UTC, yakky approved these changes

2019-12-14 17:04 UTC, merged