Update conf.py template
italia/docs.italia.it pull request #55
Opened 2018-06-27 15:27 UTC by pdavide

2018-06-27 15:34 UTC, xrmx requested changes

2018-06-27 15:34 UTC, xrmx commented on readthedocs/templates/doc_builder/conf.py.tmpl
> +html_title = u'{{ project.name }}
missing '

2018-06-27 15:34 UTC, xrmx commented on readthedocs/templates/doc_builder/conf.py.tmpl
> +  ('index', {{ project.slug }} + '.tex', u'{{ project.name }}, u'{{ project.publisherproject.first.publisher.name }}, 'manual'),
strings must be enclosed with '

2018-06-27 15:34 UTC, xrmx commented on readthedocs/templates/doc_builder/conf.py.tmpl
> +latex_show_urls = 'footnote
missing '

2018-06-27 16:36 UTC, xrmx reviewed
If you can please squash the two commit it's fine for me

2018-07-02 07:54 UTC, yakky approved these changes

2018-07-02 07:54 UTC, yakky commented
@xrmx is this ok for you now?

2018-07-02 07:55 UTC, xrmx approved these changes

2018-07-02 07:55 UTC, merged