Few fixes / amends in order to cleanup the UI
italia/docs.italia.it pull request #57
Opened 2018-06-28 16:27 UTC by francescozaia

- User menu
- "Cos'è docs italia" page
- Log out page
- Homepage Search box
- Language selection dropdown

2018-06-30 07:17 UTC, xrmx approved these changes

2018-07-02 07:34 UTC, francescozaia commented
@yakky ho aggiunto un rapido commit che completa la [scheda su Trello](https://trello.com/c/4HLob6un/68-correzioni-tema), quando riesci puoi darci un occhio e mergiare, grazie!

2018-07-02 07:37 UTC, xrmx requested changes

2018-07-02 07:37 UTC, xrmx commented on readthedocs/templates/docsitalia/overrides/projects/project_dashboard_base.html
> +  {% comment %}
please don't :) remove don't comment

2018-07-02 07:37 UTC, xrmx commented on readthedocs/templates/docsitalia/overrides/projects/project_dashboard.html
> +{% block dashboard-onboard-extra %}
The right fix is the following:

```
{% block dashboard-onboard-extra %}{% endblock %}
```

2018-07-02 07:49 UTC, francescozaia commented on readthedocs/templates/docsitalia/overrides/projects/project_dashboard_base.html
> +  {% comment %}
👍

2018-07-02 07:50 UTC, francescozaia commented on readthedocs/templates/docsitalia/overrides/projects/project_dashboard.html
> +{% block dashboard-onboard-extra %}
grazie, sistemo subito

2018-07-02 07:50 UTC, yakky requested changes
Can you check the minor changes reported?

2018-07-02 07:50 UTC, yakky commented on readthedocs/templates/docsitalia/includes/header.html
> +            {% comment %}
Any reason not to remove this?

2018-07-02 07:50 UTC, yakky commented on readthedocs/templates/docsitalia/includes/user_menu.html
> +    {% if user.get_full_name %}
I am not sure we have `user` in the context. Maybe `request.user` ?

2018-07-02 07:50 UTC, yakky commented on readthedocs/templates/docsitalia/overrides/core/header.html
> +          {% comment %}{% gravatar request.user.email 24 %}% endcomment %}
Maybe we should just remove this?

2018-07-02 07:50 UTC, yakky commented on readthedocs/templates/docsitalia/overrides/projects/project_dashboard_base.html
> +  {% comment %}
Maybe we should just remove this?

2018-07-02 10:26 UTC, yakky approved these changes

2018-07-02 10:27 UTC, yakky commented
LGTM. Waiting for @xrmx review to merge

2018-07-02 10:28 UTC, xrmx approved these changes

2018-07-02 21:29 UTC, merged