Hotfix/remove badge link and onclick event
italia/docs.italia.it pull request #62
Opened 2018-07-06 14:49 UTC by protoroto

Remove link from badge and remove badge markup code included below (it was opening below the badge when clicking on it)

2018-07-06 15:54 UTC, francescozaia requested changes
Ci sarebbero due cosette da vedere:
- se quell'`include` (`badge_markup.html`) serve ancora e, in caso contrario, rimuoverlo.
- aggiungere un testo alternativo `alt` all'immagine. Se non c'è di meglio, puoi usare `{% trans "Badge" %}` anche lì.

2018-07-06 17:13 UTC, yakky commented
@francescozaia intendi rimuovere il template? se vogliamo semplificare il rebase su upstream conviene lasciarlo, secondo me

2018-07-09 06:56 UTC, francescozaia commented
Ok np allora, lasciamolo!

2018-07-09 07:57 UTC, francescozaia approved these changes

2018-07-09 07:59 UTC, francescozaia commented
Lascio a voi _squash and merge_, per me è ok.

2018-07-09 08:13 UTC, merged