Force python version in tox
italia/docs.italia.it pull request #64
Opened 2018-07-07 14:06 UTC by yakky

2018-07-09 06:55 UTC, francescozaia submitted a review, later dismissed
LGTM

2018-07-09 07:09 UTC, xrmx requested changes
Unless I'm missing something we are now running just 3 tests instead of the full testsuite

2018-07-09 08:11 UTC, yakky commented
@xrmx :man_facepalming: my bad. i read the travis output the wrong way. Removed travis changes, only tox python version

2018-07-10 07:41 UTC, xrmx approved these changes

2018-07-10 07:41 UTC, merged